apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: scaler-sample
spec:
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: sample_session_total
      target:
        type: AverageValue
        averageValue: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scaler-sample